spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/playtech_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format-sql: true
    open-in-view: false # Optimization for Hibernate